<?php
/**
 * Turning one pasted block of text into a FAQ list, and back again.
 *
 * The edit screen used to be a repeater: two inputs per question, a button to
 * add another. That is a lot of clicking to enter something an editor almost
 * always already has as plain text — drafted in a doc, generated by an
 * assistant, or copied off the page it is answering. So the field is a single
 * textarea now, and this file is the translation layer between what someone
 * pastes and the {q, a} pairs the accordion and the FAQPage schema consume.
 *
 * Three input shapes are accepted, in this order of preference:
 *
 *   1. Explicit markers, which win wherever they appear because they are
 *      unambiguous — an answer may then run to as many lines as it likes:
 *
 *          Q: How long does a website take?
 *          A: Four to six weeks for a standard business site.
 *
 *   2. Blank-line separated blocks — first line the question, the rest the
 *      answer:
 *
 *          How long does a website take?
 *          Four to six weeks for a standard business site.
 *
 *          What does it cost?
 *          From BDT 25,000.
 *
 *   3. No blank lines at all, in which case any line ending in a question
 *      mark starts a new question and everything after it is the answer.
 *
 * @package ssbd
 */

defined( 'ABSPATH' ) || exit;

/**
 * Marker patterns. Bengali forms are listed because that is the language the
 * questions are often drafted in, even on an English page.
 */
/*
 * ঃ (U+0983, Bengali visarga) is included alongside the ASCII punctuation:
 * it is the character Bengali writing actually uses where English uses a
 * colon, so "প্রশ্নঃ" is the ordinary, expected way to write "Q:" in Bengali —
 * not a typo to tolerate, the normal spelling to match.
 */
const SSBD_FAQ_Q_MARKER = '/^\s*[*_]{0,2}\s*(?:Q|Ques|Question|প্রশ্ন|প্র)\s*[:.)ঃ\-–]\s*[*_]{0,2}\s*/iu';
const SSBD_FAQ_A_MARKER = '/^\s*[*_]{0,2}\s*(?:A|Ans|Answer|উত্তর|উ)\s*[:.)ঃ\-–]\s*[*_]{0,2}\s*/iu';

/**
 * Strip list numbering, bullets and markdown emphasis from a question line.
 *
 * Pasted lists arrive as "1. How much…" or "- How much…" far more often than
 * not, and the numbering is presentation, not part of the question.
 *
 * @param string $line Raw line.
 * @return string
 */
function ssbd_faq_clean_line( $line ) {
	$line = preg_replace( '/^\s*(?:\d+\s*[.)]|[-*•·])\s+/u', '', (string) $line );
	$line = preg_replace( '/^\s*[*_]{1,2}\s*|\s*[*_]{1,2}\s*$/u', '', (string) $line );

	return trim( (string) $line );
}

/**
 * Parse pasted FAQ text into question/answer pairs.
 *
 * @param string $text Raw textarea content.
 * @return array<int, array{q: string, a: string}>
 */
function ssbd_faq_parse_text( $text ) {
	/*
	 * A paste from a rich-text source — Google Docs, a chat app's own editor,
	 * sometimes the browser's own paste handling for a formatted clipboard —
	 * often carries U+2028/U+2029 (Unicode line/paragraph separator) instead
	 * of "\n" for its line breaks. explode( "\n", … ) never saw a line break
	 * in that text at all: the whole paste arrived as one line, none of the
	 * three parse strategies below had a boundary to work with, and the field
	 * saved as empty with nothing on screen to explain why. A plain \r\n/\r
	 * source never carries these, so normalising them here is free for
	 * everyone else.
	 *
	 * U+00A0 (non-breaking space) is normalised too: it does not match \s in
	 * a PCRE pattern, so "Q:\u{a0}How long…" — one space, spent as an
	 * NBSP by the same class of paste — would not match SSBD_FAQ_Q_MARKER's
	 * \s* even though it looks identical to a person reading it.
	 */
	$text = str_replace(
		array( "\r\n", "\r", "\xE2\x80\xA8", "\xE2\x80\xA9", "\xC2\xA0" ),
		array( "\n", "\n", "\n", "\n", ' ' ),
		(string) $text
	);

	if ( '' === trim( $text ) ) {
		return array();
	}

	$lines = explode( "\n", $text );

	foreach ( $lines as $line ) {
		if ( preg_match( SSBD_FAQ_Q_MARKER, $line ) ) {
			return ssbd_faq_parse_marked( $lines );
		}
	}

	// A blank line is only a block separator when there is more than one block;
	// a single trailing newline is not a signal about structure.
	$blocks = preg_split( '/\n\s*\n+/', trim( $text ) );

	return count( $blocks ) > 1
		? ssbd_faq_parse_blocks( $blocks )
		: ssbd_faq_parse_questions( $lines );
}

/**
 * Parse the explicit "Q:" / "A:" form.
 *
 * @param string[] $lines Lines of the field.
 * @return array<int, array{q: string, a: string}>
 */
function ssbd_faq_parse_marked( $lines ) {
	$items   = array();
	$current = null;
	$target  = 'q';

	foreach ( $lines as $line ) {
		if ( preg_match( SSBD_FAQ_Q_MARKER, $line ) ) {
			if ( $current ) {
				$items[] = $current;
			}

			$current = array(
				'q' => ssbd_faq_clean_line( preg_replace( SSBD_FAQ_Q_MARKER, '', $line ) ),
				'a' => '',
			);
			$target  = 'q';
			continue;
		}

		if ( null === $current ) {
			// Anything before the first Q: is a preamble, not part of a pair.
			continue;
		}

		if ( preg_match( SSBD_FAQ_A_MARKER, $line ) ) {
			$target          = 'a';
			$current['a']    = trim( $current['a'] . ' ' . trim( (string) preg_replace( SSBD_FAQ_A_MARKER, '', $line ) ) );
			continue;
		}

		if ( '' === trim( $line ) ) {
			continue;
		}

		// A continuation line. Before an "A:" appears it extends the question,
		// which is how a question wrapped across two lines survives.
		$current[ $target ] = trim( $current[ $target ] . ' ' . trim( $line ) );
	}

	if ( $current ) {
		$items[] = $current;
	}

	return ssbd_faq_filter_pairs( $items );
}

/**
 * Parse blank-line separated blocks: first line question, rest the answer.
 *
 * @param string[] $blocks Blocks of text.
 * @return array<int, array{q: string, a: string}>
 */
function ssbd_faq_parse_blocks( $blocks ) {
	$items = array();

	foreach ( $blocks as $block ) {
		$lines = array_values( array_filter( array_map( 'trim', explode( "\n", $block ) ), 'strlen' ) );

		if ( count( $lines ) < 2 ) {
			continue;
		}

		$items[] = array(
			'q' => ssbd_faq_clean_line( array_shift( $lines ) ),
			'a' => trim( implode( ' ', $lines ) ),
		);
	}

	return ssbd_faq_filter_pairs( $items );
}

/**
 * Parse a run of lines where a question mark ends each question.
 *
 * @param string[] $lines Lines of the field.
 * @return array<int, array{q: string, a: string}>
 */
function ssbd_faq_parse_questions( $lines ) {
	$items   = array();
	$current = null;

	foreach ( $lines as $line ) {
		$line = trim( $line );

		if ( '' === $line ) {
			continue;
		}

		if ( str_ends_with( $line, '?' ) || str_ends_with( $line, '？' ) ) {
			if ( $current ) {
				$items[] = $current;
			}

			$current = array(
				'q' => ssbd_faq_clean_line( $line ),
				'a' => '',
			);
			continue;
		}

		if ( null === $current ) {
			continue;
		}

		$current['a'] = trim( $current['a'] . ' ' . $line );
	}

	if ( $current ) {
		$items[] = $current;
	}

	return ssbd_faq_filter_pairs( $items );
}

/**
 * Drop half-written pairs. A question with no answer cannot go into FAQPage
 * structured data, and an answer with no question is not a FAQ entry.
 *
 * @param array $items Parsed pairs.
 * @return array<int, array{q: string, a: string}>
 */
function ssbd_faq_filter_pairs( $items ) {
	return array_values( array_filter(
		$items,
		static function ( $item ) {
			return '' !== trim( (string) $item['q'] ) && '' !== trim( (string) $item['a'] );
		}
	) );
}

/**
 * Render stored pairs back into the textarea's canonical form.
 *
 * Always the explicit marker form, so what comes back out of the field parses
 * identically to what went in however it was originally written.
 *
 * @param array $items FAQ pairs.
 * @return string
 */
function ssbd_faq_to_text( $items ) {
	$blocks = array();

	foreach ( (array) $items as $item ) {
		$q = trim( (string) ( $item['q'] ?? '' ) );
		$a = trim( (string) ( $item['a'] ?? '' ) );

		if ( '' === $q || '' === $a ) {
			continue;
		}

		$blocks[] = "Q: {$q}\nA: {$a}";
	}

	return implode( "\n\n", $blocks );
}
